export const allBranches = [
    {
        id: "1",
        name: "Sri Raghavendra Swamy Matha - Atlanta (RAMA)",
        description: "1060 Rocky Road, Lawrenceville, GA 30044",
        phone: "Pradeep Vittalmurthy: +1 (404) 939-2833",
        email: "info@atlantarayaramath.org",
        website: "https://atlantarayaramath.org/",
    },
    {
        id: "2",
        name: "Sri Raghavendra Swamy Matha - GB SRS Brindavan, London, UK",
        description:
            "Sivers House Unit 1, White Hart Road, Slough, UK SL1 2SF (Reg Charity No 1150660)",
        phone: "Matha: +44 7500 067891, Srihari: +44 7887 360024",
        email: "info@gb-srsbrundavan.org",
        website: "https://gb-srsbrundavan.org",
    },
    {
        id: "3",
        name: "Sri Raghavendra Swamy Matha - SRS Brundavan Midwest Branch, Chicago",
        description: "7 Wood Oaks Drive, South Barrington, Illinois 60010",
        phone: "Nagarajan Venugopalan: +1 (630) 251-2739, Sunil Rao: +1 (847) 387-0881",
        email: "vnagas@gmail.com",
    },
    {
        id: "4",
        name: "Sri Raghavendra Swamy Matha - SRS Brindavan Midwest, Chicagoland Area",
        description: "462 N McLean Blvd, Elgin, IL - 60123",
        phone: "Office Contact: +1 (847) 857-7761",
        email: "info@il-srsmatha.org",
    },
    {
        id: "5",
        name: "Sri Raghavendra Swamy Matha - SRS Brundavan Midwest Branch, Boston",
        description: "95 Front Street, Shirley, MA 01464, U.S.A",
        phone: "Tel: +1 (978) 425-7077, Srinivas Kulkarni: +1 (781) 718-3718",
    },
    {
        id: "6",
        name: "Sri Raghavendra Swamy Matha - SRSPM Melbourne, Australia",
        description: "64 Central Road, Hampton Park, Vic 3976, Australia",
        phone:
            "Venkatesh Achar: +61 468 729 161, Gururajan Nagarajan: +61 414 784 777",
        email: "srspmmelb@gmail.com",
    },
];

export const IndianBranches = [
    {
        id: "1",
        name: "Sri Bhuvanendra Teertha Vrindavana",
        description: "Sri Raghavendra Swamy Matha, Rajoli, Dist. Mahaboob Nagar",
        phone: "Not Available",
    },
    {
        id: "2",
        name: "Sri Raghavendra Swamy Mutt - Badepally",
        description: "Sri Raghavendra Swamy Matha, Badepally - 509 301, Dist: Mahaboob Nagar",
        phone: "Not Available",
    },
    {
        id: "3",
        name: "Sri Raghavendra Swamy Mutt - Tirupati",
        description: "18, RS Gardens, Tirupati - 517 507",
        phone: "0877 - 2230338",
    },
    {
        id: "4",
        name: "Sri Raghavendra Swamy Mutt - Ramantapur, Hyderabad",
        description: "3-12-3/HC, Ganesh Nagar, Ramantapur, Hyderabad - 27",
        phone: "040 - 27039146",
    },
    {
        id: "5",
        name: "Sri Raghavendra Swamy Mutt - Rayachoti",
        description: "Brahmin Street, Rayachoti, Dist: Kadapa",
        phone: "Not Available",
    },
    {
        id: "6",
        name: "Sri Raghavendra Swamy Mutt - Jogeshwari, Mumbai",
        description: "Near Oshivara Bridge, Gulshan Nagar, Jogeshwari (W), Mumbai – 400 102",
        phone: "022 – 26785678",
    },
    {
        id: "7",
        name: "Sri Raghavendra Swamy Mutt - Gadwal",
        description: "Rajaveedhi, Gadwal, Dist: Mahaboob Nagar",
        phone: "08546 – 274442",
    },
    {
        id: "8",
        name: "Sri Raghavendra Swamy Mutt - Tunga Bhadra",
        description: "Railway Station Road, Tunga Bhadra 518 397, Dist: Kurnool",
        phone: "08512 – 259808",
    },
    {
        id: "9",
        name: "Sri Raghavendra Swamy Mutt - Kolhapur",
        description: "Mahadvara Road, Kolhapur",
        phone: "Not Available",
    },
    {
        id: "10",
        name: "Sri Raghavendra Swamy Mutt - Rameshwaram",
        description: "H.No 2/14, New Street, Rameshwaram, Ramantapuram Dist – 623526",
        phone: "04573 – 223789 / 9445988722",
    },
    {
        id: "11",
        name: "Sri Mangaraya Anjaneya Swamy Temple",
        description: "Sri Raghavendra Swamy Mutt, Adoni – 518 301",
        phone: "08512 – 252505",
    },
    {
        id: "12",
        name: "Sri Raghavendra Swamy Mutt - Barkat Pura, Hyderabad",
        description: "Barkat Pura, Hyderabad",
        phone: "040 – 27560170",
    },
    {
        id: "13",
        name: "Sri Raghavendra Swamy Mutt - Dharmavaram",
        description: "State Bank of India Colony, Dharmavaram 515 671, Dist: Anantapur",
        phone: "08554 – 22744",
    },
    {
        id: "14",
        name: "Sri Raghavendra Swamy Mutt - Malkajgiri, Secunderabad",
        description: "Sri Venkateswara Nagar, Malkajgiri, Secunderabad – 47",
        phone: "040 – 27052697",
    },
    {
        id: "15",
        name: "Sri Raghavendra Swamy Mutt - Kadiri",
        description: "Near Lakshminarasimha Swamy Temple, Brahmin Street, Kadiri",
        phone: "08494 – 222189",
    },
    {
        id: "16",
        name: "Sri Raghavendra Swamy Mutt - Warangal",
        description: "Parimalagiri Colony, Vaddepally Mandal, PO: Hanmakonda, Dist: Warangal",
        phone: "0870 – 252849",
    },
    {
        id: "17",
        name: "Sri Raghavendra Swamy Mutt - Margao",
        description: "Motidonger, Gomanchal Colony, Margao",
        phone: "0832 – 2736063",
    },
    {
        id: "18",
        name: "Sri Raghavendra Swamy Mutt - Tirumala Hills",
        description: "Medar Mitta, Ring Road, Tirumala Hills – 517 504",
        phone: "0877 – 2277302",
    },
    {
        id: "19",
        name: "Sri Raghavendra Swamy Mutt - Badrinath Dham",
        description: "Near Brahma Kapal, Badrinath Dham, Uttaranchal",
        phone: "Not Available",
    },
    {
        id: "20",
        name: "Sri Raghavendra Swamy Matha - New Delhi",
        description: "Rao Tularam Marg, Near Motibagh Flyover, Sector 12, RK Puram, New Delhi",
        phone: "011 – 26172892 / 9444310442",
    },
    {
        id: "21",
        name: "Sri Lakshmi Narasimha Swamy Temple - Kurnool",
        description: "Sri Raghavendra Swamy Mutt Fort, Kurnool",
        phone: "08518 – 244498",
    },
    {
        id: "22",
        name: "Sri Raghavendra Swamy Mutt - Penukonda",
        description: "Matham Street, Penukonda, Dist: Anantapur",
        phone: "9247605162",
    },
    {
        id: "23",
        name: "Sri Yadavendra Teerthara Brindavana - Mudumala",
        description: "Sri Raghavendra Swamy Matha, Mudumala, Dist: Mahaboob Nagar",
        phone: "Not Available",
    },
    {
        id: "24",
        name: "Sri Raghavendra Swamy Mutt - Solapur",
        description: "Raghavendra Nagar, Morarjipet, Solapur – 400 102",
        phone: "0217 – 2727345",
    },
    {
        id: "25",
        name: "Sri Raghavendra Swamy Mutt - Chittoor",
        description: "Sri Sugunendra Teerthara Moola Vrindavana Sannidhana, Greamspet, Brahmin Street, Chittoor – 517 001",
        phone: "Not Available",
    },
    {
        id: "26",
        name: "Sri Raghavendra Swamy Mutt - Mahaboob Nagar",
        description: "Parimalagiri, Mahaboob Nagar 509 022",
        phone: "08542 – 242034",
    },
    {
        id: "27",
        name: "Sri Raghavendra Swamy Mutt - Tirupati",
        description: "R.E. Mada Street, Tirupati",
        phone: "Not Available",
    },
    {
        id: "28",
        name: "Sri Raghavendra Swamy Mutt - Solapur",
        description: "Railway Colony, Solapur",
        phone: "Not Available",
    },
];
