export const guruParampare = [
"Sri Hamsanamaka Paramatma",
"Sri Chaturmukha Brahma",
"Sri Sanaka Teertharu",
"Sri Sanandana Teertharu",
"Sri Sanatkumara Teertharu",
"Sri Sanatana Teertharu",
"Sri Doorvasa Teertharu",
"Sri Jnananidhi Teertharu",
"Sri Garuda vahana Teertharu",
"Sri Kaivalya Teertharu",
"Sri Jnanesha Teertharu",
"Sri ParaTeertharu",
"Sri Satyaprajna Teertharu",
"Sri Prajna Teertharu",
"Sri Achyutaprekshacaryaru",
"Sri Madhwacharyaru",
"Sri Padmanabha Teertharu",
"Sri Narahari Teertharu",
"Sri Madhava Teertharu",
"Sri Akshobhya Teertharu",
"Sri Jayateertharu",
"Shri Vidyadhiraja Teertharu",
"Shri Kaveendra Teertharu",
"Shri Vaageesha Teertharu",
"Shri Ramachandra Teertharu",
"Shri Vibudhendra Teertharu",
"Shri Jitamitra Teertharu",
"Shri Raghunandana Teertharu",
"Shri Surendra Teertharu",
"Shri Vijayeendra Teertharu",
"Sri Sudheendra Teertharu",
"Sri Raghavendra Teertharu",
"Sri Yogeendra Teertharu",
"Sri Sooreendra Teertharu",
"Sri Sumateendra Teertharu",
"Sri Upendra Teeertharu",
"Sri Vadeendra Teertharu",
"Sri Vasudhendra Teertharu",
"Sri Varadendra Teertharu",
"Sri Dheerendra Teertharu",
"Sri Bhuvanendra Teertharu",
"Sri Subodhendra Teertharu",
"Sri Sujanendra Teertaru",
"Sri Sujnanendra Teertharu",
"Sri Sudharmendra Teertharu",
"Sri Sugunendra Teertharu",
"Sri Suprajnendra Teertharu",
"Sri Sukrutheendra Teertharu",
"Sri Susheelendra Teertharu",
"Sri Suvrateendra Teertharu",
"Sri Suyameendra Teertharu",
"Sri Sujayeendra Teertharu",
"Sri Sushameendra Teertharu",
"Shri Suyateendra Teertharu",
"Sri Subudhendra Teertharu – Present Pontiff "]